name = "JuFE"
uuid = "756825e7-608a-4815-acaf-db43c38ec120"
authors = ["Nolan Strauss"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
